version: '3'

services:
  server:
    container_name: "moinho.network.server"
    build: tile-server/
    command: node index.js
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      VIRTUAL_HOST: server.moinho.network
      LETSENCRYPT_HOST: server.moinho.network
      LETSENCRYPT_EMAIL: luandro@gmail.com
      PORT: 3000
      VIRTUAL_PORT: 3000
  web:
    container_name: "moinho.network"
    image: httpd:latest
    restart: unless-stopped
    ports:
      - 8083:80
    volumes:
      -  ./html/:/usr/local/apache2/htdocs/
    environment:
      VIRTUAL_HOST: moinho.network,www.moinho.network
      LETSENCRYPT_HOST: moinho.network,www.moinho.network
      LETSENCRYPT_EMAIL: luandro@gmail.com
networks:
  default:
    external:
      name: nginx-proxy
