version: '3'
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
  ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ssl
    environment:
      - NGINX_PROXY_CONTAINER=proxy
    volumes:
      - certs:/etc/nginx/certs
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
  whoami:
    image: jwilder/whoami
    ports:
      - "8000:8000"
    environment:
      - VIRTUAL_HOST=whoami.luandro.com
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=whoami.luandro.com
      - LETSENCRYPT_EMAIL=luandro@gmail.com
volumes: 
  certs:
  html:
  vhostd:
