version: '3'
services:
  proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    networks:
     - nginx-proxy
    environment:
      - DEFAULT_HOST=0.0.0.0
  ssl:
    image: nginxproxy/acme-companion:latest
    container_name: ssl
    environment:
      - NGINX_PROXY_CONTAINER=proxy
    volumes:
      - certs:/etc/nginx/certs
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    networks:
      - nginx-proxy
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    restart: always
    networks:
      - nginx-proxy
  whoami:
    image: jwilder/whoami:latest
    ports:
      - "8000:8000"
    environment:
      - VIRTUAL_HOST=whoami.luandro.com
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=whoami.luandro.com
      - LETSENCRYPT_EMAIL=luandro@gmail.com
    networks:
      - nginx-proxy
volumes: 
  certs:
  html:
  vhostd:
networks:
  nginx-proxy:
    external:
      name: nginx-proxy
