version: '3'

services:
  web:
    container_name: "kaapora"
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      -  ./html/:/usr/share/nginx/html
    environment:
      VIRTUAL_HOST: kaapora.luandro.com
      LETSENCRYPT_HOST: kaapora.luandro.com
      LETSENCRYPT_EMAIL: luandro@gmail.com
networks:
  default:
    external:
      name: nginx-proxy
volumes:
  db_data:
