version: '3'

services:
  db:
    container_name: ${CONTAINER_DB_NAME}
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ${DB_PATH}:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    depends_on:
      - db
    container_name: ${CONTAINER_WP_NAME}
    image: wordpress:latest
    restart: unless-stopped
    volumes:
      - ./wp-app:/var/www/html # Full wordpress project
      - ./conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      WORDPRESS_DB_HOST: ${CONTAINER_DB_NAME}:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE:-200k}
  wpcli:
    image: wordpress:cli
    depends_on:
      - db
      - wordpress
    restart: 'no'
    volumes:
      - ./wp-app:/var/www/html # SHOULD BE VAR
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini # SHOULD BE VAR
    user: xfs
networks:
  default:
    external:
      name: ${NETWORK}
volumes:
  db_data:
