version: '3'

services:
  web:
    container_name: "luandro.com"
    image: httpd:latest
    restart: unless-stopped
    volumes:
      -  ./html/:/usr/local/apache2/htdocs/
    environment:
      VIRTUAL_HOST: luandro.com,www.luandro.com
      LETSENCRYPT_HOST: luandro.com,www.luandro.com
      LETSENCRYPT_EMAIL: luandro@gmail.com
networks:
  default:
    external:
      name: nginx-proxy
volumes:
  db_data:
