version: '3'

services:
  pad:
    container_name: "etherpad"
    image: etherpad/etherpad
    restart: unless-stopped
    environment:
      TITLE: ${TITLE}
      DEFAULT_PAD_TEXT¨: ${DEFAULT_PAD_TEXT}
      PAD_OPTIONS_LANG: ${PAD_OPTIONS_LANG}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      VIRTUAL_HOST: pad.luandro.com
      LETSENCRYPT_HOST: pad.luandro.com
      LETSENCRYPT_EMAIL: luandro@gmail.com
networks:
  default:
    external:
      name: nginx-proxy