version: '2'
services:
  web:
    image: php:latest
    volumes:
      - ./app:/var/www/html
    environment:
      VIRTUAL_HOST: '${HOST}'
      LETSENCRYPT_HOST: '${HOST}'
      LETSENCRYPT_EMAIL: '${EMAIL}'
    command: wget --no-check-certificate -O master.zip $GIT_URL
