version: '2'
services:
    nginx-proxy:
      image: jwilder/nginx-proxy
      restart: always
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - "./nginx/vhost.d:/etc/nginx/vhost.d"
        - "./nginx/html:/usr/share/nginx/html"
        - "./nginx/certs:/etc/nginx/certs"
        - "/var/run/docker.sock:/tmp/docker.sock:ro"
    letsencrypt-nginx-proxy-companion:
      image: jrcs/letsencrypt-nginx-proxy-companion
      restart: always
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
      volumes_from:
        - "nginx-proxy"
    rancher-server:
      image: rancher/server:stable
      restart: unless-stopped
      # environment:
        # no_proxy: "localhost,127.0.0.1"
        # NO_PROXY: "localhost,127.0.0.1"
        # http_proxy: luandro.com
        # https_proxy: luandro.com
        # VIRTUAL_HOST: luandro.com
        # LETSENCRYPT_HOST: luandro.com
        # LETSENCRYPT_EMAIL: luandro@gmail.com
        
    #   volumes:
    #     - /path/to/mysql/ca.crt:/var/lib/rancher/etc/ssl/ca.crt
      ports:
        - "8080:8080"