version: '3'

services:
  web:
    container_name: "pirania.coolab.org"
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html
    environment:
      VIRTUAL_HOST: pirania.coolab.org
      LETSENCRYPT_HOST: pirania.coolab.org
      LETSENCRYPT_EMAIL: luandro@gmail.com
networks:
  default:
    external:
      name: nginx-proxy
