services:
  broker:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data
    
  db:
    image: mariadb:10.6
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${PAPERLESS_DBNAME:-paperless}
      MYSQL_USER: ${PAPERLESS_DBUSER:-paperless}
      MYSQL_PASSWORD: ${PAPERLESS_DBPASS:-paperless}
      MYSQL_ROOT_PASSWORD: ${PAPERLESS_DBPASS:-paperless}
      MYSQL_SSL: "false"

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBPORT: 3306
      PAPERLESS_DBNAME: ${PAPERLESS_DBNAME:-paperless}
      PAPERLESS_DBUSER: ${PAPERLESS_DBUSER:-paperless}
      PAPERLESS_DBPASS: ${PAPERLESS_DBPASS:-paperless}
      PAPERLESS_DBSSLMODE: "disable"
      VIRTUAL_HOST: docs.luandro.com
      LETSENCRYPT_HOST: docs.luandro.com  
      LETSENCRYPT_EMAIL: luandro@gmail.com
      VIRTUAL_PORT: 8000

networks:
  default:
    name: nginx-proxy
    external: true

volumes:
  data:
  media:
  dbdata:
  redisdata:
