ethercalc:
  image: audreyt/ethercalc
  restart: unless-stopped
  environment:
    REDIS_PORT_6379_TCP_ADDR: redis
    REDIS_PORT_6379_TCP_PORT: 6379
    VIRTUAL_HOST: calc.luandro.com
    LETSENCRYPT_HOST: calc.luandro.com
    LETSENCRYPT_EMAIL: luandro@gmail.com

  links:
    - redis:redis
redis:
  image: redis:latest
  volumes:
    - /var/lib/redis:/data
  command: redis-server --appendonly yes
  restart: unless-stopped
