version: "3.8"

services:
  kotaemon:
    image: ghcr.io/cinnamon/kotaemon:main-full
    container_name: kotaemon
    ports:
      - 7860:7860
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - VIRTUAL_HOST=rag.luandro.com
      - VIRTUAL_PORT=7860
      - LETSENCRYPT_HOST=rag.luandro.com
      - LETSENCRYPT_EMAIL=luandro@gmail.com
    restart: always
networks:
  default:
    external:
      name: nginx-proxy
